### ISSUE TITLE
Publish 1.6.0 release version

### ISSUE THREAD

**Issue by ZerglingGo** [marcelodolza/iziModal#178]
I think this plugin updated to 1.6.0. But repository hasn't 1.6.0 release.
Please publishing version 1.6.0.

Thank you for useful plugin!

**Comment by ZerglingGo** [comment]
I created a [fork repository](https://github.com/ZerglingGo/iziModal) as a temporary solution for using v1.6.0 on npm.

**Comment by eman1986** [comment]
looks like 1.6 isn't published anywhere from what I see, but its advertised on the website.

**Comment by mixplace** [comment]
please publish v1.6.0 to npm repository.

**Comment by combs** [comment]
@dolce can you please publish 1.6.0 to npm

**Comment by MIKNOTAURO** [comment]
Any updates about this guys?
