### ISSUE TITLE
Page scrolls to top when modal opens.

### ISSUE THREAD

**Issue by berpcor** [marcelodolza/iziModal#229]
I don't want to change iziModals for something else, how to solve the problem?

**Comment by raczger** [comment]
In iziModal.js remove this line (488):
`$('html').addClass(PLUGIN_NAME+'-isOverflow');`
And this too (644):
`$('html').removeClass(PLUGIN_NAME+'-isOverflow');`

**Comment by Feltim** [comment]
On version 1.6.1 this is again an issue - "Main Page scroll is reset to left top when Modal opens."
The suggested lines of code is not on exact same line number, which makes me believe the problem was reintroduced in later version.

Removing the suggested lines does not resolve the issue.
