### ISSUE TITLE
error after open

### ISSUE THREAD

**Issue by NathanielB2** [marcelodolza/iziModal#231]
hello,

In Firefox I'm getting the error TypeError: this.$element.find(...)[0] is undefined and it because code that gets the contentHeight. 

contentHeight = this.$element.find('.'+PLUGIN_NAME+'-content')[0].scrollHeight,

If I set it to say contentHeight = 500,  it works fine but the size is incorrect. 

I'm opening the iziModal using .iziModal('open'); after ajax success.  The iziModal is set on $(document).ready.  

What do i do to get the height set so this error goes away?

Thanks

**Comment by NathanielB2** [comment]
I figured it out.  I don't know I needed to have a inner div with the content and class iziModal-content.

**Comment by SimplyBallistic** [comment]
> I figured it out. I don't know I needed to have a inner div with the content and class iziModal-content.

Close the issue if you are done
