### ISSUE TITLE
Remove Popup ID 

### ISSUE THREAD

**Issue by monzuralam** [marcelodolza/iziModal#245]
### is there any way to remove the popup id in the address bar when the popup loaded?

When Window load then show a popup. is there any way to remove the popup id in the address bar when the popup loaded?
for more details check the screenshot:
[https://prnt.sc/172qj39](https://prnt.sc/172qj39)

**Current URL:** 
[https://test.example.com/#popup](https://test.example.com/#popup)
**Expected URL:** 
[https://test.example.com](https://test.example.com)

![issue](https://user-images.githubusercontent.com/46376609/123541056-286f0d00-d764-11eb-81f4-1ef1bf47ff7d.png)

**Comment by Anshu-jindal** [comment]
Try commenting line 72 in iziModal/js/iziModal.js

window.location.hash = hash
